# https://github.com/adi-g15/archlinux-repository/blob/master/.github/workflows/build.yaml
name: Update records

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "30 */12 * * *" # Run at 7:00 Indian Standard Time (+5:30)

env:
  GIT_REMOTE: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: ./scripts/script.sh githubaction
      with:
        path: scripts # REQUIRED. Kyunki ../data/

# ex: shiftwidth=2 expandtab:
